### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by parikshithmj** [mmalecki/hock#28]
So from what i understand, i can launch a nodeJs server and customize the API's to return based on my params and payload ?
So i just try to launch the server with the following code, but i get an error. Where am i going wrong ?

$$ > node filename.js

var http = require('http'),
        hock = require('hock'),
        request = require('request');

    var mock = hock.createHock();
    mock.get('/url').reply(200, 'Hello!');

    var server = http.createServer(mock.handler);
    server.listen(9090, function () {
        request('http://localhost:' + 9090 + '/url', function(err, res, body) {
           console.log(body);
        });
    });
******************
Error : 
/Users/pjagadeesh/hockTest/node_modules/hock/lib/hock.js:28
  this._throwOnUnmatched = (typeof options.throwOnUnmatched === 'boolean' ? op
                                          ^
TypeError: Cannot read property 'throwOnUnmatched' of undefined

**Comment by mmalecki** [comment]
Hey there!

Sorry for the late reply. It looks like you're using an outdated version of hock. I just ran your example and it works on the recently published 1.3.2. You can upgrade your version of hock by running `npm i hock@latest`.

I'm going to close this issue, but feel free to either ping me here to reopen the issue or create a new one.
