### ISSUE TITLE
Question : why not depend directly on nock ?

### ISSUE THREAD

**Issue by bannier** [mmalecki/hock#37]
Hi, I was considering building an http interface to nock when I discovered hock that looks very close to what I need.
But when I opened package.json I saw you didn't depend on nock.
I was wondering why you chose not to forward configurations requests to actual nock ? Doesn't it suit your needs ?

**Comment by mmalecki** [comment]
Hi there! Hm, we haven't even considered this when writing hock. I believe we could have used nock's logic without its monkey patching, but writing our own just made sense at the time, since we needed very little features.

Feel free to reopen if you have any more questions!
